name: Deploy Monorepo (Frontend + Backend)

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    steps:
      - uses: actions/checkout@v4

      - name: Detectar cambios
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Wait deploy
        run: sleep 60

      - name: Health check backend
        run: |
          for i in {1..10}; do
            curl -f https://usuarios-eventos-app.onrender.com/ && exit 0
            sleep 5
          done
          exit 1

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Crear build
        working-directory: frontend
        run: |
          mkdir ../dist
          cp -r index.html css js ../dist/

      - name: Subir artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4